CSharp-Technical-Challenge/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharp_Technical_Challenge.Models;
using CSharp_Technical_Challenge.Models.ViewModels;

namespace MVCCrud.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            List<EmployeeList> lst;
            using (DBShoppingEntities db = new DBShoppingEntities())
            {
                lst = (from d in db.Employee
                       select new EmployeeList
                       {
                           ID = d.ID,
                           Name = d.Name,
                           Telephone = d.Telephone,
                           EmploymentDate = (DateTime)d.EmploymentDate
                       }).ToList();
            }
            return View(lst);
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(CSharp_Technical_Challenge.Models.ViewModels.Employee model)
        {
              if (ModelState.IsValid)
              {
                    try
                    {

                        using (DBShoppingEntities db = new DBShoppingEntities())
                        {

                            var table = new CSharp_Technical_Challenge.Models.Employee();
                            table.Name = model.Name;
                            table.Type = model.Type;
                            table.Telephone = model.Telephone;
                            table.Address = model.Address;
                            table.EmploymentDate = model.EmploymentDate;

                            db.Employee.Add(table);
                            db.SaveChanges();

                        }
                        return Redirect("~/Employee/");
                    }
                     catch (Exception ex)
                    {
                        return Content("<script language='javascript' type='text/javascript'>alert('" + ex.Message + "');</script>");

                    }

              }
         return Redirect("~/Employee/");
    }

        public ActionResult Edit(int id)
        {
            CSharp_Technical_Challenge.Models.ViewModels.Employee model = new CSharp_Technical_Challenge.Models.ViewModels.Employee();

            using (DBShoppingEntities db = new DBShoppingEntities())
            {
                var table = db.Employee.Find(id);
                model.ID = table.ID;
                model.Name = table.Name;
                model.Type = table.Type;
                model.Telephone = table.Telephone;
                model.Address = table.Address;
                model.EmploymentDate = (DateTime)table.EmploymentDate;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CSharp_Technical_Challenge.Models.ViewModels.Employee model)
        {       
                if (ModelState.IsValid)
                {
                    try
                    {
                        using (DBShoppingEntities db = new DBShoppingEntities())
                        {

                            var table = db.Employee.Find(model.ID);
                            table.Name = model.Name;
                            table.Type = model.Type;
                            table.Telephone = model.Telephone;
                            table.Address = model.Address;
                            table.EmploymentDate = model.EmploymentDate;

                            db.Entry(table).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();

                        }
                        return Redirect("~/Employee/");
                    }
                    catch (Exception ex)
                    {
                        return Content("<script language='javascript' type='text/javascript'>alert('" + ex.Message + "');</script>");

                    }
                    
                }
            return Redirect("~/Employee/");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            using (DBShoppingEntities db = new DBShoppingEntities())
            {
                var table = db.Employee.Find(Id);

                db.Employee.Remove(table);
                db.SaveChanges();
            }
            return Redirect("~/Employee/");
        }
    }
}

CSharp-Technical-Challenge/Controllers/EmployeeTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharp_Technical_Challenge.Models;
using CSharp_Technical_Challenge.Models.ViewModels;

namespace MVCCrud.Controllers
{
    public class EmployeeTypeController : Controller
    {
        // GET: EmployeType
        public ActionResult Index()
        {
            List<EmployeeTypeList> lst;
            using (DBShoppingEntities db = new DBShoppingEntities())
            {
                lst = (from d in db.EmployeeType
                       select new EmployeeTypeList
                       {
                           ID = d.ID,
                           Name = d.Name,
                           Salary = (int)d.Salary
                       }).ToList();
            }
            return View(lst);
        }
    }
}

CSharp-Technical-Challenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My C# Technical Challenge</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My C# Technical Challenge", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Types of Employee", "Index", "EmployeeType")</li>
                    <li>@Html.ActionLink("Shop", "Index", "Shop")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My C# Technical Challenge</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>